### ISSUE TITLE
Multi Lib

### ISSUE THREAD

**Issue by Pixeltech285** [Lepisma-0/Extended-Tech#1]
Hello, it appears the mod need a multi lib, and I cannot locate such a thing

![Screenshot_20221011-180422_Mindustry](https://user-images.githubusercontent.com/111621604/195220081-45b613a6-c49e-4534-aa33-476facc003d9.jpg)

**Comment by Lepsima** [comment]
The mod doesn't work good on the new versions of v7 (erekir), because of some code changes and maybe the multi-lib mod isn't the same on v7, i will try to make it stable for v6 / no erekir v7

**Comment by Lepsima** [comment]
Now it works for v135, (needs multi-lib but in v6 it appears on the mod search)

**Comment by Pixeltech285** [comment]
> Now it works for v135, (needs multi-lib but in v6 it appears on the mod search)

Ah, I see, so it's only compatible on V6? (Also, feel free to lemme know when I am being dumb, I know nothing about coding)

**Comment by Lepsima** [comment]
No worries, it was my fault because i set the version to be compatible with v7 to try it, and didnt change back, now it should work only in v6
